version: '3'

services:
  pandora-next:
    image: q11391/pandora-helper
    container_name: PandoraHelper
    network_mode: bridge
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./data:/app/data